vertx:
  server:
    port: 80

  handler-mappings:
    - path: /demo
      method: GET
      beanNames: homeHandler,demoHandler

    - path: /block
      method: GET
      beanNames: blockedCallHandler

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 20
  instance:
    prefer-ip-address: true
