vertx:
  server:
    port: 8080

  handler-mappings:
    - path: /demo
      method: GET
      beanNames: homeHandler,demoHandler

    - path: /block
      method: GET
      beanNames: blockedCallHandler

